kind: DataScienceCluster
apiVersion: datasciencecluster.opendatahub.io/v1
metadata:
  name: default
spec:
  components:
    modelregistry:
      managementState: Removed
      registriesNamespace: rhoai-model-registries
