apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ai-example-single-model-serving

helmCharts:
- name: vllm-kserve
  releaseName: granite
  version: 0.3.7
  repo: https://Anusha2605.github.io/helm-charts/
  valuesFile: values.yaml
